### ISSUE TITLE
Can not be installed on Heroku

### ISSUE THREAD

**Issue by somyabn** [tenderlove/av_capture#8]
When i tried to push my application to Heroku it cant install the av_capture gem.

**Comment by pnc** [comment]
@somyabn Unfortunately, that's expected! This gem will only build on OS X, since it depends on the libraries Apple provides for capturing from the built-in webcam.

If you're building a website and need to use the user's webcam, you'll want to look at the HTML5 `getUserMedia()` APIs to capture video from JavaScript: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
